export enum DocumentProcedureTypeEnum {
  LEGALIZACION_DIPLOMA_BACHILLER = "LEGALIZACION_DIPLOMA_BACHILLER",
  LEGALIZACION_DIPLOMA_ACADEMICO = "LEGALIZACION_DIPLOMA_ACADEMICO",
  LEGALIZACION_TITULO_PROVISION_NACIONAL = "LEGALIZACION_TITULO_PROVISION_NACIONAL"
}
