export enum ProcedureStatusEnum {
  ADMIN_REVIEW = "ADMIN_REVIEW",
  ARCHIVES_REVIEW = "ARCHIVES_REVIEW",
  SECRETARY_REVIEW = "SECRETARY_REVIEW",
  ADMIN_FINAL_REVIEW = "ADMIN_FINAL_REVIEW",
  COMPLETED = "COMPLETED",
  REJECTED = "REJECTED",
  PENDING = "PENDING"
}
